language: c
# Container is faster to spin than the VM
sudo: false
# Need 14.04 for a recent enough CMake
# Not bad to have more recent clang and gcc
dist: trusty

addons:
  apt:
    # Need to fetch from the source.  Here is the motherload:
    # https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
    - llvm-toolchain-trusty-4.0
    - ubuntu-toolchain-r-test
    packages:
    - xorg-dev                  # needed by GLFW
    - valgrind
    - clang-4.0                 # bleeding edge
    - gcc-7

matrix:
  include:

  # GCC build, but do not fail on -Werror here as there are warnings we haven't
  # heeded yet.
  - compiler: gcc-7

  # Latest clang build
  - compiler: clang-4.0
    env:
    - FLAGS="-Werror"

  # Undefined behavior sanitizer
  - compiler: clang-4.0
    env:
    - FLAGS="-fsanitize=undefined -fno-sanitize-recover=undefined -DALL_WINDOWS -DTIMEOUT=100000000"
    - RUN=debug

  # Address sanitizer
  - compiler: clang-4.0
    env:
    - FLAGS="-fsanitize=address -O1 -fno-omit-frame-pointer -DALL_WINDOWS -DTIMEOUT=100000000"
    - RUN=debug
    - LSAN_OPTIONS="suppressions=lsan.supp"
    - ASAN_OPTIONS="fast_unwind_on_malloc=0"

  # Valgrind
  - compiler: clang-4.0
    env:
    - RUN=valgrind
    - FLAGS="-DALL_WINDOWS -DTIMEOUT=10000"

# Build and install deps/ locally
install: ./install-deps.sh

# Run a virtual frame buffer (xvfb) rather than disabling the window
# see https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

script:
- make -j2 CC=$CC USER_FLAGS="$FLAGS" BUILD_DIR=build/debug
- |
  case $RUN in
    debug)
      ./run.sh debug roms/daytrip.bin
       ;;
    valgrind)
      ./run.sh -r 'valgrind --leak-check=full --error-exitcode=1'\
                   debug roms/daytrip.bin
      ;;
  esac
